apiVersion: k0rdent.mirantis.com/v1beta1
kind: ClusterTemplate
metadata:
  annotations:
    helm.sh/resource-policy: keep
  labels:
    k0rdent.mirantis.com/component: kcm
  name: aws-hybrid-arch-standalone-1-0-0
  namespace: kcm-system
spec:
  helm:
    chartSpec:
      chart: ./charts/aws-hybrid-arch-standalone
      interval: 10m0s
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: custom-templates
      version: 1.0.0
