apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackCluster
metadata:
  name: {{ include "cluster.name" . }}
spec:
  disableAPIServerFloatingIP: true
  {{- if .Values.bastion.enabled }}
  bastion:
  {{- with .Values.bastion.spec }}
    spec:
      {{- toYaml . | nindent 8 }}
  {{- end }}
  {{- end }}
  {{- if .Values.externalNetwork }}
  externalNetwork:
    {{- toYaml .Values.externalNetwork | nindent 4 }}
  {{- end }}
  identityRef:
    name: {{ .Values.clusterIdentity.name }}
    cloudName: {{ .Values.identityRef.cloudName | default "openstack" }}
    region: {{ .Values.identityRef.region | default "RegionOne" }}
    type: {{ .Values.identityRef.type | default "Secret" }}
  {{- if .Values.managedSecurityGroups }}
  managedSecurityGroups:
    {{- toYaml .Values.managedSecurityGroups | nindent 4 }}
  {{- end }}
  {{- if .Values.network }}
  network:
    {{- toYaml .Values.network | nindent 4 }}
  {{- end }}
  {{- if .Values.subnets }}
  subnets:
    {{- toYaml .Values.subnets | nindent 4 }}
  {{- end }}
  {{- if .Values.router }}
  router:
    {{- toYaml .Values.router | nindent 4 }}
  {{- end }}
